# -*- coding: utf-8 -*-
"""talller1MS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_HK1CfCcaVNRhs7tyGqBN2rTemERI5iE
"""

class Vehiculo:
  catalogo=[]
  def __init__(self,engine:int,chasis:str,model:str,year:str,tipo:str):
    self.engine=engine
    self.chasis=chasis
    self.model=model
    self.year=year
    self.tipo=tipo
    print("se creo el carro")
    print(engine,chasis,model,year,tipo)
  def guardar(self):
    gas_cons=self.consumption()
    datos=[self.engine,self.chasis,self.model,self.year,self.tipo,gas_cons]
    self.catalogo.append(datos)
  def referencia(self):
      if self.chasis=="A":
          return 0.3
      elif self.chasis=="B":
          return 0.5
      else:
        return 0.2
  def masa(self):
    if self.tipo=="coche":
      return 200
    elif self.tipo=="camion":
      return 400
    elif self.tipo=="yate":
      return 600
    elif self.tipo=="motocicleta":
      return 100
    else:
      pes=int(input("no exite el nombre del veiculo ingrese su peso:"))
      return pes
  def fuerza(self):
    if self.tipo=="coche":
      return 25*self.engine
    elif self.tipo=="camion":
      return 20*self.engine
    elif self.tipo=="yate":
      return 55*self.engine
    elif self.tipo=="motocicleta":
      return 10*self.engine
    else:
      pes=int(input("no exite el nombre del veiculo ingrese su pontencia:"))
      return pes

  def consumption(self):
    referci=self.referencia()
    pontencial=self.fuerza()
    peso=self.masa()
    gas=float((1.1*pontencial)+(0.2*peso)-(referci))
    return gas

import pandas as pd
information="""
Opcion 1. crear vehiculo

opcion 8. salir
"""
print(information)
option=int(input("Ingresar opcion"))
while option!=8:
  if option==1:
    print("creas vehiculo, profavor ingresar los siquientes datos")
    en=int(input("cuantos motores tienene:"))
    ch=(input("el chasis es A o B:"))
    mo=(input("el modelo es:"))
    ay=(input("el año es:"))
    tip=(input("el tipo de vehiculo es:"))
    a1=Vehiculo(en,ch,mo,ay,tip)
    print(a1.consumption())
  elif option==2:
    print(a1=)
  print(information)
  option=int(input("Ingresar opcion"))